## 1. Generate dataset
Python code to generate a classification dataset that contains 10000 examples.

In this dataset, each 2-dimensional input $\textbf{x} = (x_1, x_2)$ is drawn uniformly random from the set $[0, 1] \times [0, 1]$ and the corresponding output is

$y = sign(x_2 - x_1 + \epsilon),$

where $\epsilon$ is Gaussian noise with zero mean and standard deviation 0.1, and
  
  $sign(z) =   \begin{cases}
    1, & \text{for } z>0 \\
    -1, & \text{for } z<0 \\
    0 & \text{for } x=0
  \end{cases}$

In [ ]:
import numpy as np
np.random.seed(0)
num_examples = 10000
X = np.random.rand(num_examples, 2)
gaussian = 0.1 * np.random.randn(num_examples)
y = np.sign(X[:, 1] - X[:, 0] + gaussian)
print("Input (X):")
print(X[:5])
print("Output (y):")
print(y[:5])

Input (X):
[[0.5488135  0.71518937]
 [0.60276338 0.54488318]
 [0.4236548  0.64589411]
 [0.43758721 0.891773  ]
 [0.96366276 0.38344152]]
Output (y):
[ 1. -1.  1.  1. -1.]


## 2. Split dataset into train/test sets


In [ ]:
from sklearn.model_selection import train_test_split
import numpy as np

X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42)

print(np.shape(X_train))

(8000, 2)


## 3. Define and train a K-NN model



In [ ]:
from sklearn import neighbors
from sklearn.neighbors import KNeighborsClassifier

clock = KNeighborsClassifier(n_neighbors= 5)
clock.fit(X_train, y_train)

KNeighborsClassifier()

## 4. Make prediction with your K-NN model



In [ ]:
Y_prod= clock.predict(X_test)
print(Y_prod)

[-1. -1.  1. ... -1. -1. -1.]


\## 5. Compute the accuracy



In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(clock.predict(X_test), y_test)*100

91.85

## 6. Repeating the experiments with a logistic regression model




In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
logisticRegr = LogisticRegression()
logisticRegr.fit(X_train, y_train)

LogisticRegression()

In [ ]:
y_pred = logisticRegr.predict(X_test)
print(y_pred)
accuracy = accuracy_score(y_test,y_pred)*100
print(accuracy)

[-1. -1.  1. ... -1. -1. -1.]
92.60000000000001


## 8. Repeating the experiments with a SVM Classifier



In [ ]:
from sklearn import svm
from sklearn.metrics import accuracy_score
#Create a svm Classifier
Support = svm.SVC(kernel='linear') # Linear Kernel

#Train the model using the training sets
Support.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = Support.predict(X_test)
accuracy_score(S.predict(X_test), y_test)*100

91.95

## 10. Compare the three classifiers



According to the above results, Logistic regression is the best due to accuracy. By comparing 3 accuracies Logistic regression is having the highest accuracy.