# Numpy Demo

Source: https://becominghuman.ai/an-essential-guide-to-numpy-for-machine-learning-in-python-5615e1758301

This demo only contains a subset of the tutorial above. Please try this demo and the whole tutorial above at home.

### 1. Import the library

First, we need to import the numpy library to use. Here `np` will be used as an abbreviation for `numpy`.

In [ ]:
import numpy as np

### 2. Create a vector

In [ ]:
# Create a row vector from a list
vector_row = np.array([1,2,3])

# Create a column vector from a list of lists
vector_column = np.array([[1],[2],[3]])

print(vector_row)
print(vector_column)

[1 2 3]
[[1]
 [2]
 [3]]


### 3. Create a matrix

In [ ]:
# Create a matrix from a list of lists
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

print(matrix)

[[1 2 3]
 [4 5 6]]


### 4. Select elements

In [ ]:
# Print 2nd element of vector_row
print(vector_row[1])

# Print 3rd column of vector_column
print(vector_column[2])

# Print element at 1st row, 3rd column of matrix
print(matrix[0,2])

# Print sub-matrix with 2nd row and first two columns
print(matrix[1:,:2])

2
[3]
3
[[4 5]]


### 5. Properties of a matrix

In [ ]:
matrix = np.array([[1, 2, 3, 10],
                   [4, 5, 6, 11],
                   [7, 8, 9, 12]])

# Print number of rows and columns
print(matrix.shape)

# Print number of rows and columns separately
print(matrix.shape[0])
print(matrix.shape[1])

# Print number of elements
print(matrix.size)

# Print number of dimensions
print(matrix.ndim)

(3, 4)
3
4
12
2


### 6. Modifying a matrix

In [ ]:
matrix = np.array([[1, 2, 3, 10],
                   [4, 5, 6, 11],
                   [7, 8, 9, 12]])

matrix[0, 3] = 20
print(matrix)

matrix += 5
print(matrix)

matrix = matrix / 2
print(matrix)

matrix[1] = matrix[0]*2
print(matrix)

[[ 1  2  3 20]
 [ 4  5  6 11]
 [ 7  8  9 12]]
[[ 6  7  8 25]
 [ 9 10 11 16]
 [12 13 14 17]]
[[ 3.   3.5  4.  12.5]
 [ 4.5  5.   5.5  8. ]
 [ 6.   6.5  7.   8.5]]
[[ 3.   3.5  4.  12.5]
 [ 6.   7.   8.  25. ]
 [ 6.   6.5  7.   8.5]]


### 7. Find min and max elements

In [ ]:
matrix = np.array([[1, 2, 3, 10],
                   [4, 5, 6, 11],
                   [7, 8, 9, 12]])

# Print max and min elements
print(np.max(matrix))
print(np.min(matrix))

# Print max element in each column
print(np.max(matrix, axis=0))

# Print min element in each row
print(np.min(matrix, axis=1))

12
1
[ 7  8  9 12]
[1 4 7]


### 8. Reshape and transpose

In [ ]:
# Create a vector
vector = np.arange(12)
print(vector)

# Reshape the vector into a matrix
matrix = vector.reshape(4, 3)
print(matrix)

# Transpose the matrix
matrix = np.transpose(matrix)
print(matrix)

# Flatten the new matrix
print(matrix.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
[ 0  3  6  9  1  4  7 10  2  5  8 11]


### 9. Matrix operations

In [ ]:
m1 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
m2 = np.array([[7, 8, 9],
               [4, 5, 6],
               [1, 2, 3]])

# Element-wise sum, subtraction, multiplication
print(m1+m2)
print(m1-m2)
print(m1*m2)

# Matrix multiplication
print(np.matmul(m1, m2))

[[ 8 10 12]
 [ 8 10 12]
 [ 8 10 12]]
[[-6 -6 -6]
 [ 0  0  0]
 [ 6  6  6]]
[[ 7 16 27]
 [16 25 36]
 [ 7 16 27]]
[[ 18  24  30]
 [ 54  69  84]
 [ 90 114 138]]


### 10. Random number generator

In [ ]:
# Generate random integers uniformly from low to high-1
low = 1
high = 10
print(np.random.randint(low, high))
print(np.random.randint(low, high))
print(np.random.randint(low, high))
print(np.random.randint(low, high))

0
1
1
1
0
2
3
0
1
8
8
2
3


In [ ]:
# Generate random samples from a normal distribution with given mean and standard deviation
m = 2
std = 0.5

print(np.random.normal(m, std))
print(np.random.normal(m, std))
print(np.random.normal(m, std))